name: 'TypeDoc'
author: 'Zakodium'
description: 'Build documentation using TypeDoc'
inputs:
  entry:
    description: 'Entry point of your API'
    required: true
    default: 'src/index.ts'
  treatWarningsAsErrors:
    description: 'Treat warnings as errors'
    required: false
    default: 'false'

  name:
    description: 'Name of the package'
runs:
  using: 'node20'
  main: 'index.mjs'
